// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLU5Jgmp33tftL4rLTF7kavDXoK40Youk',
    appId: '1:78400260654:web:c5df347f2875cfc7576dbf',
    messagingSenderId: '78400260654',
    projectId: 'al-madar-bridge',
    authDomain: 'al-madar-bridge.firebaseapp.com',
    storageBucket: 'al-madar-bridge.firebasestorage.app',
    measurementId: 'G-JG4E8P4K6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAK3J1Ak8-ruKhoNdwqp-HId3hHk3VOKQ',
    appId: '1:78400260654:android:28c02324120a3c75576dbf',
    messagingSenderId: '78400260654',
    projectId: 'al-madar-bridge',
    storageBucket: 'al-madar-bridge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5BdGjKb8sqEN0aoCxIsY2o8AEU3qrakM',
    appId: '1:78400260654:ios:1c433fe5bee1b4d7576dbf',
    messagingSenderId: '78400260654',
    projectId: 'al-madar-bridge',
    storageBucket: 'al-madar-bridge.firebasestorage.app',
    iosBundleId: 'com.example.alMadarBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5BdGjKb8sqEN0aoCxIsY2o8AEU3qrakM',
    appId: '1:78400260654:ios:1c433fe5bee1b4d7576dbf',
    messagingSenderId: '78400260654',
    projectId: 'al-madar-bridge',
    storageBucket: 'al-madar-bridge.firebasestorage.app',
    iosBundleId: 'com.example.alMadarBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLU5Jgmp33tftL4rLTF7kavDXoK40Youk',
    appId: '1:78400260654:web:0b58794d8f551405576dbf',
    messagingSenderId: '78400260654',
    projectId: 'al-madar-bridge',
    authDomain: 'al-madar-bridge.firebaseapp.com',
    storageBucket: 'al-madar-bridge.firebasestorage.app',
    measurementId: 'G-0CS3WPXL1R',
  );
}
